### PR TITLE
Some features/fixes/updates

### PR DESCRIPTION
**Pull request by jcgruenhage**
Hey, so I was looking into writing something like this and was pleased that most of the work was already done.
Here are the fixes I created before deploying this thing, any thoughts on them?

### CODE REVIEW

**Comment by jcgruenhage** [comment]
I made my commits according to https://www.conventionalcommits.org/en/v1.0.0/, assuming that that's roughly what you use from what I saw in the repo. Each commit should contain a description of the changes and the motivation there.

**Comment by zbrox** [comment]
Hey @jcgruenhage, this is super helpful. I was postponing for a while to migrate to proper logging and to the API tokens. And a good catch on that cache bug. 

Thanks again! I will merge this right away. Will update the README and then release 0.3.0.

**Comment by jcgruenhage** [comment]
Awesome! I think there's some more things we could do here, like using cloudflare-rs instead of calling the API ourselves and caching more than just the IP (zone ID and record ID for example), maybe throwing some async into the mix too. Are you interested in that? Didn't want to change stuff too much in my first PR :D

**Comment by zbrox** [comment]
Oh, I wasn't aware of clouflare-rs, will check it out. Caching more is a good idea we can look into. Recently I was looking to sprinkling some async with async-rs but eventually since it's just a couple of dependent calls and they're pretty fast I dropped the idea out of laziness. But just purely for the exercise of it and to try out more async-rs stuff I'm not against it. I'm using this on some machines and as long as it's working as expected and fairly fast it's ok with me :)

**Pull request merged**
